sudo: false

language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
      - python-libvirt
      - python3-libvirt

install: pip install tox-travis

script: tox
